kanta = float(input("Syötä suorakulmion kanta: "))
korkeus = float(input("Syötä suorakulmion korkeus: "))
pintaala = (kanta*korkeus)
piiri = ((kanta+korkeus)*2)
print(f"Suorakulmion pinta-ala on: {pintaala}\nSuorakulmion piiri on: {piiri}")