leiviska = float(input("Anna leiviskät: "))
naula = float(input("Anna naulat: "))
luoti = float(input("Anna luodit: "))
massakg = ((((((leiviska*20)+naula)*32)+luoti)*13.3)/1000)
print(f"Massa on {massakg[:-10]}kg ja {massakg: 0.10f}g")